from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
import os

class ListingTest:
    def __init__(self):
        self.driver = webdriver.Chrome()
        self.url = "http://localhost:3000"
        self.image_path = os.path.abspath("dummy.jpg")

    def run_test(self):
        driver = self.driver
        driver.get(self.url)
        driver.maximize_window()
        time.sleep(2)

        driver.find_element(By.ID, 'login_button').click()
        time.sleep(1)
        driver.find_element(By.ID, 'email').send_keys("rijad1@gmail.com")
        driver.find_element(By.ID, 'password').send_keys("The7stick-")
        driver.find_element(By.ID, 'submit_button').click()
        time.sleep(1)

        driver.get(f"{self.url}/profile/902")
        driver.find_element(By.ID, "add_new_listing").click()
        time.sleep(2)

        driver.find_element(By.ID, "title").send_keys("Test Car Listing")
        Select(driver.find_element(By.ID, "manufacturer")).select_by_visible_text("Toyota")
        driver.find_element(By.ID, "model").send_keys("Corolla")
        driver.find_element(By.ID, "yearOfManufacture").send_keys("2019")
        driver.find_element(By.ID, "engineSize").send_keys("1800")
        driver.find_element(By.ID, "kw").send_keys("97")
        driver.find_element(By.ID, "distanceTraveled").send_keys("75000")
        Select(driver.find_element(By.ID, "fuelType")).select_by_visible_text("Benzin")
        Select(driver.find_element(By.ID, "city")).select_by_visible_text("Sarajevo")
        driver.find_element(By.ID, "price").send_keys("15000")
        driver.find_element(By.ID, "description").send_keys("This is a test listing generated by Selenium.")
        driver.find_element(By.ID, "file").send_keys(self.image_path)
        time.sleep(2)

        driver.find_element(By.XPATH, "//button[contains(text(), 'Add Listing')]").click()
        time.sleep(2)

        assert driver.current_url == f"{self.url}/profile/902", "Expected to be redirected to profile page"
        driver.quit()

test = ListingTest()
test.run_test()
